// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjZGvT2YPsr3VXU92j2LG1rE6oIoTmB-4',
    appId: '1:405946145382:web:196d06ec310b8f92762ba7',
    messagingSenderId: '405946145382',
    projectId: 'todo-app-gso42-aprilia',
    authDomain: 'todo-app-gso42-aprilia.firebaseapp.com',
    storageBucket: 'todo-app-gso42-aprilia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvi90O7b1t-iaR4eH_FdVAB_hAG2QFxdE',
    appId: '1:405946145382:android:d589f086cd06eee1762ba7',
    messagingSenderId: '405946145382',
    projectId: 'todo-app-gso42-aprilia',
    storageBucket: 'todo-app-gso42-aprilia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNu4TlDy8k5IwySjRosO8zHIQpFYglSPc',
    appId: '1:405946145382:ios:d1de1f4a701b30f5762ba7',
    messagingSenderId: '405946145382',
    projectId: 'todo-app-gso42-aprilia',
    storageBucket: 'todo-app-gso42-aprilia.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
